on:
  push:
  create:
jobs:
  update:
    name: Updating the service pack
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Dump github event
      id: a
      run: echo '${{ github.event.action }}'
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
    - name: Dump steps context
      run: echo '${{ toJSON(steps) }}'
    - name: Dump runner context
      run: echo '${{ toJSON(runner) }}'
    - name: Dump strategy context
      run: echo '${{ toJSON(strategy) }}'
    - name: Dump matrix context
      run: echo '${{ toJSON(matrix) }}'
    - name: Checking out repository
      uses: actions/checkout@v3
    - name: Updating service pack
      uses: MatthiasVandersanden/service-pack-update@main
      with:
        token: ${{ github.token }}
        path: "${{ github.workspace }}/config.json"
    - name: Commit and push changes to remote
      uses: actions-js/push@master
      with:
        github_token: ${{ github.token }}
        message: "Updating config"
