on:
  create
jobs:
  update:
    name: Updating the service pack
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repository
      uses: actions/checkout@v3
    - name: Updating service pack
      uses: MatthiasVandersanden/service-pack-update@v1.0
      with:
        token: ${{ github.token }}
        path: "${{ github.workspace }}/config.json"
