on:
  create:
  push:
jobs:
  update:
    name: Updating the service pack
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Checking out repository
      uses: actions/checkout@v3
    - name: Tagging commit
      if: github.event_name == 'push'
      uses: MatthiasVandersanden/vectorworks-tag@v1.0
      with:
        token: ${{ github.token }}
        path: "${{ github.workspace }}/config.json"
    - name: Updating service pack
      if: github.event_name == 'create' && startsWith(github.ref, 'refs/heads/')
      id: update
      uses: MatthiasVandersanden/service-pack-update@main
      with:
        token: ${{ github.token }}
        path: "${{ github.workspace }}/config.json"
    - name: Commit and push changes to remote
      if: github.event_name == 'create' && startsWith(github.ref, 'refs/heads/') && steps.update.updated == true
      uses: actions-js/push@master
      with:
        github_token: ${{ github.token }}
        message: "Updating config"
        branch: ${{ github.ref }}
